### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by bonelifer** [Cyanistic/mpdtrackr#1]
Will there be install instructions?

**Comment by Cyanistic** [comment]
The instructions are rather simple, grab the latest release for your OS from releases, put it where you put your binaries, and make sure its executable, then just run it like you would for any other command line program. On Linux download it, make it executable with `chmod +x` , and copy it to `/usr/bin` . Then you can run mpdtrackr from the terminal.  If you want it to run on startup you can use the functions provided by your window manager/desktop environment or use the `mpdtrackr.service` file by downloading it, copying it to `/usr/lib/systemd/user`, and running `systemctl --user enable --now mpdtrackr.service` if you use systemd. I didn't add any install instructions because I thought they would be rather pointless since they are the same as pretty much every other program. I could add an installation section to the README or an install.sh if you think it would be helpful.

**Comment by Cyanistic** [comment]
I have added an installation section in the README and an install.sh in the latest commit which should help make installation relatively straightforward.
